# Generated by Django 4.2.6 on 2023-10-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_owner_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('to_order', 'Под заказ')], max_length=50),
        ),
    ]
